server:
#  port: ${PORT:8080}
  port: 8080

spring:
  application:
    name: goodFirstIssueBot

  profiles:
    active: ${APP_ENV:dev}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

github_token: ${GITHUB_TOKEN}

telegram-bot:
  webhook-path: https://b8ec-185-90-100-153.ngrok.io
  bot-username: goodfirstissue_bot
  bot-token: ${TG_BOT_TOKEN}
